.TH DBGINFO.SH  1 "November 2012" "s390-tools"
 
.SH NAME
dbginfo.sh \- collect runtime, configuration and trace information
for debugging Linux on System z

.SH SYNOPSIS
.br
\fBdbginfo.sh\fP {\-h|\-v}

.SH DESCRIPTION
This script collects runtime, configuration and trace information that can
be used to debug a Linux on System z instance.
For Linux on z/VM, the script also traces information about the z/VM system.
The debug information is written to a file
/tmp/DBGINFO\-<date>\-<time>\-<hostname>\-<processorid>.tgz
where [date] and [time] are the date and time when the debug data was
collected. [hostname] indicates the hostname of the system the data was
collected from. The [processorid] is taken from the processor 0 and indicates
the processor identification.

.SH OPTIONS
.TP
\fB\-h\fP, \fB\-\-help\fP
Print usage information, then exit.

.TP
\fB\-v\fP, \fB\-\-version\fP
Print version information, then exit.

.SH FILES
A .tgz file of the form
.PP
.nf
.fam C
    DBGINFO\-<year>\-<month>\-<day>\-<hours>\-<minutes>\-<seconds>\-<hostname>\-<processorid>.tgz

.fam T
.fi
is generated and placed in the /tmp directory.

.SH EXAMPLE
Sample invocation:
.P
[root@host]# dbginfo.sh
.br
 dbginfo.sh: Debug information script version %S390_TOOLS_VERSION%
.br
 Copyright IBM Corp. 2002, 2012
.PP
 Hardware platform     = s390x
.br
 Kernel version        = 3.0.13 (3.0.13\-0.27\-default)
.br
 Runtime environment   = z/VM
.PP
 1 of 7: Collecting command output
.PP
 2 of 7: Collecting z/VM command output
.PP
 3 of 7: Collecting procfs
.PP
 4 of 7: Collecting sysfs
.PP
 5 of 7: Collecting log files
.PP
 6 of 7: Collecting config files
.PP
 7 of 7: Collecting osa oat output skipped
.PP
 Finalizing: Creating archive with collected data
.PP
 Collected data was saved to:
.br
 >>  /tmp/DBGINFO\-2012\-10\-14\-13\-10\-42-host-123456.tgz  <<
.SH HINTS
Run the script with root authority.
.br
For Linux on z/VM, only z/VM guest virtual machines with class B privileges
yield the complete debug information.
.SH AUTHOR
Linux on System z development <linux390@de.ibm.com>
